name: safety
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  carousel_slider: ^4.2.1
  webview_flutter: ^4.7.0
  flutter_phone_direct_caller: ^2.1.1
  url_launcher: ^6.2.6
  fluttertoast: ^8.2.5
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  contacts_service: ^0.6.3
  sqflite: ^2.3.3+1
  background_sms: ^0.0.4
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  image_picker: ^1.1.1
  uuid: ^4.4.0
  firebase_storage: ^11.7.5
  cached_network_image: ^3.3.1
  shake: ^2.2.0
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  flutter_local_notifications: ^17.1.2
  vibration: ^1.8.4
  telephony: ^0.2.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/